Enhance SSP service management and configuration
Added 'create_not_existing_dir' option to config and implemented directory creation logic in service.py. Improved uninstall logic and help output in ssp shell script. Updated systemd service file with CPU scheduling and capability restrictions. Updated documentation and service logic for better error handling and logging of purged services.

diff --git a/usr/sbin/ssp b/usr/sbin/ssp
--- a/usr/sbin/ssp
+++ b/usr/sbin/ssp
@@ -1,39 +1,66 @@
 #!/bin/bash
 
-uninstall(){
-    read -p "Are you sure you want to uninstall? (y/n): " confirmation
-    if [[ $confirmation == "y" || $confirmation == "Y" ]]; then
-        ## Uninstallation process
+ssp_files="/usr/local/sbin/ssp_files"
+ssp_service="/etc/systemd/system/ssp.service"
+ssp_file="/usr/local/sbin/ssp"
+etc_ssp="/etc/ssp"
+config_file="/etc/ssp.conf"
+main_service=/usr/sbin/ssp_files""
+
+uninstall() {
+    read -rp "Are you sure you want to uninstall? (y/n): " confirmation
+    if [[ "$confirmation" =~ ^[Yy]$ ]]; then
         echo "Uninstalling..."
-        # Remove the service
         sudo systemctl stop ssp
         sudo systemctl disable ssp
-        sudo rm -f /etc/systemd/system/ssp.service
-        # Remove the scripts
-        sudo rm -rd /usr/local/sbin/ssp_files
-        sudo rm -f /usr/local/sbin/ssp
-        # Remove the configuration file directory
-        sudo rm -r /etc/ssp/
+        sudo rm -f "$ssp_service"
+        sudo rm -rf "$ssp_files" "$ssp_file" "$etc_ssp"
+        # Verification
+        if [[ ! -e "$ssp_service" && ! -d "$ssp_files" && ! -f "$ssp_file" && ! -d "$etc_ssp" ]]; then
+            echo "Uninstallation successfull."
+        else
+            echo "Error: Some of the files/dirs couldn't be removed."
+            ls -ld "$ssp_service" "$ssp_files" "$ssp_file" "$etc_ssp" 2>/dev/null
+            read -rp "Do you want to retry? (y/n): " retry
+            if [[ "$retry" =~ ^[Yy]$ ]]; then
+                uninstall
+            else
+                exit 1 # Exit by cancellation
+            fi
+        fi
     else
-        echo "Uninstallation canceled."
+        echo "Uninstallation cancelled."
+        exit 1 # Exit by cancellation
     fi
 }
-
 case "$1" in
     -h|--help)
-        echo "Help in process"
+        echo "Opciones disponibles:"
+        echo "  -h, --help       Show help"
+        echo "  -v, --version    Show version"
+        echo "  -c, --config     Edit configuration file"
+        echo "  -l  --logs       Open logs folder"
+        echo "  -u, --uninstall  Desinstala el servicio y archivos relacionados"
         ;;
     -v|--version)
         echo "V2.0.0"
         ;;
     -c|--config)
-        sudo nano /etc/ssp.conf
+        sudo nano "$config_file"
+        #vim "$config_file"
         ;;
-    -u|--unstall)
+    -e|--execute)
+        #Ejecucion manual de servicio
+        python "$ssp_files/service.py"
+        ;;
+    -l|--logs)
+        cd "/var/log/ssp/" && ll
+        ;;
+    -u|--uninstall)
         uninstall
         ;;
     *)
-        echo "Option not recognised: $1"
-        exit 1
+        echo "Error: $1"
+        exit 1 # Exit by cancellation
         ;;
 esac
